"""
CRUD 연산 모듈
=====================================================

데이터베이스 CRUD 연산을 중앙에서 관리합니다.
"""

from .user import (
    create_user,
    get_user,
    get_user_by_phone,
    get_users,
    update_user,
    delete_user,
    search_users,
    get_user_with_stats,
    update_user_last_login,
    get_active_users_count,
    get_users_by_age_group,
    get_users_by_gender,
    get_recent_users,
    get_inactive_users,
    bulk_update_users,
    get_user_statistics,
    check_user_exists,
    get_user_profile_summary,
)

from .chat_log import (
    create_chat_log,
    create_chat_session,
    get_chat_log,
    get_chat_session,
    get_or_create_session,
    get_user_chat_logs,
    get_chat_history,
    get_recent_conversation,
    update_chat_log,
    update_session_stats,
    end_chat_session,
    get_user_sessions,
    get_active_sessions,
    search_chat_logs,
    get_chat_analytics,
    get_conversation_context,
    delete_chat_log,
    delete_user_chat_history,
    get_chat_statistics,
    bulk_update_vector_ids,
)

from .emotion import (
    create_emotion,
    create_emotion_summary,
    get_emotion,
    get_emotion_summary,
    get_user_emotions,
    get_emotion_history,
    update_emotion,
    delete_emotion,
    get_recent_emotions,
    get_dominant_emotion,
    get_emotion_distribution,
    get_average_emotion_score,
    get_emotion_trend,
    get_emotion_by_time_of_day,
    get_emotion_triggers,
    create_daily_emotion_summary,
    get_user_emotion_summaries,
    analyze_emotion_patterns,
    get_emotion_correlations,
    get_emotion_statistics,
    bulk_create_emotions,
    delete_old_emotions,
)

from .schedule import (
    create_schedule,
    get_schedule_by_id,
    get_user_schedules,
    update_schedule,
    delete_schedule,
    get_schedules_by_date_range,
    get_today_schedules,
    get_upcoming_schedules,
    get_overdue_schedules,
    create_schedule_log,
    get_schedule_logs,
    update_schedule_log,
    mark_schedule_completed,
    create_schedule_template,
    get_user_schedule_templates,
    increment_template_usage,
    create_reminder,
    get_pending_reminders,
    mark_reminder_sent,
    get_schedule_stats,
    get_schedule_compliance,
    search_schedules,
    batch_update_schedules,
)

__all__ = [
    # 사용자 CRUD
    "create_user",
    "get_user",
    "get_user_by_phone",
    "get_users",
    "update_user",
    "delete_user",
    "search_users",
    "get_user_with_stats",
    "update_user_last_login",
    "get_active_users_count",
    "get_users_by_age_group",
    "get_users_by_gender",
    "get_recent_users",
    "get_inactive_users",
    "bulk_update_users",
    "get_user_statistics",
    "check_user_exists",
    "get_user_profile_summary",
    
    # 채팅 CRUD
    "create_chat_log",
    "create_chat_session",
    "get_chat_log",
    "get_chat_session",
    "get_or_create_session",
    "get_user_chat_logs",
    "get_chat_history",
    "get_recent_conversation",
    "update_chat_log",
    "update_session_stats",
    "end_chat_session",
    "get_user_sessions",
    "get_active_sessions",
    "search_chat_logs",
    "get_chat_analytics",
    "get_conversation_context",
    "delete_chat_log",
    "delete_user_chat_history",
    "get_chat_statistics",
    "bulk_update_vector_ids",
    
    # 감정 CRUD
    "create_emotion",
    "create_emotion_summary",
    "get_emotion",
    "get_emotion_summary",
    "get_user_emotions",
    "get_emotion_history",
    "update_emotion",
    "delete_emotion",
    "get_recent_emotions",
    "get_dominant_emotion",
    "get_emotion_distribution",
    "get_average_emotion_score",
    "get_emotion_trend",
    "get_emotion_by_time_of_day",
    "get_emotion_triggers",
    "create_daily_emotion_summary",
    "get_user_emotion_summaries",
    "analyze_emotion_patterns",
    "get_emotion_correlations",
    "get_emotion_statistics",
    "bulk_create_emotions",
    "delete_old_emotions",
    
    # 일정 CRUD
    "create_schedule",
    "get_schedule_by_id",
    "get_user_schedules",
    "update_schedule",
    "delete_schedule",
    "get_schedules_by_date_range",
    "get_today_schedules",
    "get_upcoming_schedules",
    "get_overdue_schedules",
    "create_schedule_log",
    "get_schedule_logs",
    "update_schedule_log",
    "mark_schedule_completed",
    "create_schedule_template",
    "get_user_schedule_templates",
    "increment_template_usage",
    "create_reminder",
    "get_pending_reminders",
    "mark_reminder_sent",
    "get_schedule_stats",
    "get_schedule_compliance",
    "search_schedules",
    "batch_update_schedules",
] 